### ISSUE TITLE
Sit Out functionality questionable

### ISSUE THREAD

**Issue by robinsph21** [bellosil21/pokerTexasHoldEm#7]
It was my turn, so I hit sit out on my turn, and then hit sit in again, and it seemed as if nothing happened, save my turn got skipped. I don't think that's intentional, it seems like players can just skip and maybe keep winning the pot?

**Comment by marcial21** [comment]
interesting we will look into this

**Comment by hoser21** [comment]
After review, it appear that you are describing the functionality of our sit out action. When a player sits out, they should be out of the game until they sit back in. It is as if they folded at the start of every round. This functionality is included for players who wish to take a break if they feel unlucky, want some rest, or want to wait for other players to make a move. Hence, sitting out intentionally skips your turn since the game automatically folded your hand. 

Regarding the pot, I was unable to find the players winning the pot when they are sitting out, which is the desired functionality. Whenever a player folds, they no longer can win the current round's pot.

Please let us know if you experience states other than what I just described.

**Comment by robinsph21** [comment]
I misunderstood the function of this button, this makes sense.
